### PR TITLE
fix Celestial-Enlightened

### PR DESCRIPTION
**Pull request by alpenstorm**
fixed enlightened celestial by replacing elytra with enchanted book in upgrade path

### CODE REVIEW

**Comment by EDTmagiclab** [comment]
I think enchanted book is too cheap.Maybe we should use something more expensive,for example,lodestone?

**Comment by alpenstorm** [comment]
honestly an enchanted book makes sense
eg. enlightened -> knowledge from books?

but yeah, that might work too

**Comment by EDTmagiclab** [comment]
Good idea

**Comment by Maxmani** [comment]
I've changed the upgrade logic to use the primary power key instead of use.

**Pull request closed without merging**
